---
- name: take care of my.cnf
  template:
    src: my.cnf.j2
    dest: "/opt/my.cnf.{{ item }}"
    force: yes
  with_sequence: start=1 end="{{ servers }}"

- name: Set server_id
  ini_file:
    path: "/opt/my.cnf.{{ item }}"
    option: server-id
    value: "{{ item }}"
    section: mysqld
  with_sequence: start=1 end="{{ servers }}" 
